### ISSUE TITLE
 side forces of planar wing without bank angle during turning flight 

### ISSUE THREAD

**Issue by Bill-B** [raalf/FreeWake#10]
Need to minimize side forces without bank angle. 

What does this mean?

**Comment by bramesfeld** [comment]
planar wing that turns without bank angle should have no CFy or side force, I think

**Comment by bramesfeld** [comment]
this means, a planar wing that turns without a bank angle should not develop any side forces (force in the plane of rotation), yet they currently do.

**Comment by Bill-B** [comment]
A side force is introduced in the span forces because the drag direction is defined as the velocity direction at the trailing  edge, which has a side component if the vehicle is rotating about the CG

**Comment by Bill-B** [comment]
closing, can re-open if the issue returns when comparing to LiLi
