### ISSUE TITLE
Are these forces ever used?

### ISSUE THREAD

**Issue by Bill-B** [raalf/FreeWake#19]
These forces calculated in drag? are they ever used?

https://github.com/raalf/FreeWake/blob/f45eef5e98885f43932432874a2704dd8cda7aa4/Source/drag_force.cpp#L442-L444

**Comment by bramesfeld** [comment]
Not sure. If not, maybe reuse them or remove them to save memory.

**Comment by bramesfeld** [comment]
Removed these forces and surfacePtr[i].Moment, too.
