### ISSUE TITLE
Put most current version in header of program

### ISSUE THREAD

**Issue by bramesfeld** [raalf/FreeWake#31]
Update that when program is executed, it also includes a date of the version that is being used.

**Comment by Bill-B** [comment]
It is pretty easy to get the git version and date of last commit at the time of running the exe, but that may not be the same as the git version that was compiled.  Getting that is more difficult, since we will need some code to be executed only when compiling. We will have to have a different way of compiling I think.

**Comment by Bill-B** [comment]
do you just want the date when the code was compiled? or the latest git version when the code was compiled? But that will not account for any changes the user has made and not committed. what is this for?

**Comment by bramesfeld** [comment]
I think having the date of the last commit is maybe the most reasonable, even if it does not include any not-yet committed changes. The purpose is to later be able to distinguish versions, for example, when you want to get back to an older version.
In general, we need to come up with a "release" method. Jan, for example, has no idea whether the version that he is using is still the most current as he continuous to implement changes to Vogen (which I should share with you sometimes).

**Comment by Bill-B** [comment]
The commit ID will hold the information about which status the code is in. If you want to go back to an older version, I would look at the commit history on github, and then git checkout the ID of the specific commit you want.

If we want, we can start tagging specific commits as v1.0, v1.1, etc (we can do this with git tag), then we can track specific points in the commit history as 'versions'. 

I am working on a way to have the command window print out the last git commit id, and git version (if we start using git tags) at the time of compilation. For example, it will output: 

Running Version FreeWake2020_dev
Compiled at git version v0.1-2-gc4867cc-dirty
Compiled on Wed 06/24/2020-20:58:45

The  v0.1-2-gc4867cc-dirty means that the version compiled is two commits after the tag v0.1. It also says the current commit is c4867cc with uncommitted changes (dirty).

If you compiled at the commit labeled v0.1, it would simply say v0.1. 

I will keep thinking about this.

**Comment by bramesfeld** [comment]
Maybe it is time to formally release FreeWake20 and move away from the developer phase, especially once the flap-dve distribution is resolved.

**Comment by Bill-B** [comment]
is this fixed? When can we move out of the development branch?
