### ISSUE TITLE
Does beta work? 

### ISSUE THREAD

**Issue by Bill-B** [raalf/FreeWake#4]
Beta has to be zero if using symmetry for force calcs:
https://github.com/raalf/FreeWake/blob/d7c7a055f97d11f3717a35ba53d89fd91990a963/Source/lift_force.cpp#L784

Not sure if lift is calculated correctly with beta:
https://github.com/raalf/FreeWake/blob/d7c7a055f97d11f3717a35ba53d89fd91990a963/Source/lift_force.cpp#L445-L449

We are not including the lift from the vortex sheets. Is this significant?

**Comment by bramesfeld** [comment]
First part is from old Horstmann code, but also exists in function for DVE method. It works.
second part works too.
Entire section will be reworked, though. N_force will be restructured.
