### ISSUE TITLE
Adding CMoWing twice to residual moment

### ISSUE THREAD

**Issue by Bill-B** [raalf/FreeWake#7]
Is the zero lift moment supposed to be added twice? but only one is added if camber is off....
https://github.com/raalf/FreeWake/blob/d83d089fc7bcff2d19f097211f65579840deee67/Source/longtrim.cpp#L78-L79

https://github.com/raalf/FreeWake/blob/d83d089fc7bcff2d19f097211f65579840deee67/Source/longtrim.cpp#L104-L105

**Comment by bramesfeld** [comment]
Line 105 adds zero-lift moment within the trim routine. It is correct, but should only be added if camber flag is off. Thus change line 104/105 to
	//adding zero lift of wing only if camber is turned off
	if(~info.flagCAMBER)    CM_resid += info.CMoWing;

**Comment by Bill-B** [comment]
fixed in d36cf245
