### ISSUE TITLE
should uTE be nondimensionalized?

### ISSUE THREAD

**Issue by Bill-B** [raalf/FreeWake#8]
When moving the elements in the ind. drag computation, should uTE be nondimensionalized? U is nondimensionalized for the non circling case...

https://github.com/raalf/FreeWake/blob/98a30096462853e13b4d9b9fc06b071f3dd85709/Source/drag_force.cpp#L220-L231

**Comment by bramesfeld** [comment]
Yes, that is correct. I can upload a corrected version or you can do that directly by changing line 223 to
tempS=dot(delX,surfacePtr[index].uTE[k])/norm2(surfacePtr[index].uTE[k]);

**Comment by Bill-B** [comment]
Needs to be changed in line 224 too, and I think it has to be done to each element of the vector. 

changed in b924607f
