### ISSUE TITLE
Fix CDi which is negative during turning flight. 

### ISSUE THREAD

**Issue by Bill-B** [raalf/FreeWake#9]
This probably requires a reference frame transformation.

**Comment by Bill-B** [comment]
CDi looks good now, it matches the CDi for straight flight if I set a large radius. I cannot make it negative. 

Leaving open because CFX is still wrong

**Comment by bramesfeld** [comment]
CFx works for turning flight in horizontal plane, still bug for turning while descending

**Comment by bramesfeld** [comment]
Fixed, problem was in function 'Circling_UINF' in wing_geometry.cpp

**Comment by bramesfeld** [comment]
Still issues, dang

**Comment by Bill-B** [comment]
beta terms will need to be included eventually:

See http://web.mit.edu/drela/Public/web/avl/avl_doc.txt
line 1602

**Comment by Bill-B** [comment]
Have a look at the eL direction inside lift_force. With horizontal geom =1, I think eL should be [0,0,1], regardless of alpha. However, without circular flight, eL = [-0.707 0 0.707], and with circ, eL = [0 0 1], even with gradient = 0 and alpha 45.

**Comment by Bill-B** [comment]
We need to better define all these directions for all the cases.  eL, eN, eS, lift, drag, CFx, CFy, CFz. Maybe a drawing. I am worried there are a few compound errors with these reference frames that may end up cancelling out towards the end, but I would rather go step by step and make sure everything is in the correct frame.

**Comment by bramesfeld** [comment]
This is why I moved from CL,CY, CD to CFX,CFY,CFZ, which should be aligned with the original ref. frame and rotates/translates. Besides, I believe that CL and CD are not correctly computed during turning flight. During  descending turning flight, in which case alpha changes, lift/drag directions change with the span. Thus, it might make more sense to resolve those loads in a body frame and add them up then.

**Comment by Bill-B** [comment]
fixed enough for now, closing
